# This is a basic workflow that is manually triggered
name: BUILD

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push,pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automake:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        node:
          # Run tests on minimal version we support
          - "17.6.0"
        NPM_CLIENT:
          # - "yarn"
          - "npm"
          # - "pnpm"
    env:
      INSTALL_PACKAGE: true
      NPM_CLIENT: ${{ matrix.NPM_CLIENT }}
    name: Test with ${{ matrix.NPM_CLIENT }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build
        run: make



